"""Add Address and DonorAddress models

Revision ID: 02ac6bc51a91
Revises: b1dabe37a177
Create Date: 2025-07-22 10:50:22.037737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02ac6bc51a91"
down_revision = "b1dabe37a177"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address_line1", sa.String(length=128), nullable=False),
        sa.Column("address_line2", sa.String(length=128), nullable=True),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "donor_addresses",
        sa.Column("donor_id", sa.Integer(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["donor_id"],
            ["donors.id"],
        ),
        sa.PrimaryKeyConstraint("donor_id", "address_id"),
    )
    with op.batch_alter_table("donors", schema=None) as batch_op:
        batch_op.drop_column("state")
        batch_op.drop_column("postal_code")
        batch_op.drop_column("city")
        batch_op.drop_column("address_line1")
        batch_op.drop_column("address_line2")
        batch_op.drop_column("country")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("country", sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("address_line2", sa.VARCHAR(length=128), nullable=True)
        )
        batch_op.add_column(
            sa.Column("address_line1", sa.VARCHAR(length=128), nullable=True)
        )
        batch_op.add_column(sa.Column("city", sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("postal_code", sa.VARCHAR(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("state", sa.VARCHAR(length=64), nullable=True))

    op.drop_table("donor_addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
