"""Add structured address fields to Donor

Revision ID: b1dabe37a177
Revises: c686b696adba
Create Date: 2025-07-13 21:49:02.067867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1dabe37a177"
down_revision = "c686b696adba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donors", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("address_line1", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(
            sa.Column("address_line2", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(sa.Column("city", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("state", sa.String(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("postal_code", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("country", sa.String(length=64), nullable=True))
        batch_op.drop_column("address")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("address", sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column("country")
        batch_op.drop_column("postal_code")
        batch_op.drop_column("state")
        batch_op.drop_column("city")
        batch_op.drop_column("address_line2")
        batch_op.drop_column("address_line1")

    # ### end Alembic commands ###
