"""Initial migration

Revision ID: c686b696adba
Revises:
Create Date: 2025-07-13 13:08:23.005765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c686b696adba"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("address", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("donors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_donors_email"), ["email"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "donations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("donor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["donor_id"],
            ["donors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("donations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_donations_date"), ["date"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_donations_date"))

    op.drop_table("donations")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("donors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_donors_email"))

    op.drop_table("donors")
    # ### end Alembic commands ###
